---
abstract: 'The great new CHI::Driver::BerkeleyDB::Manager!'
author:
  - 'James Rouzier <rouzier@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CHI-Driver-BerkeleyDB-Manager
no_index:
  directory:
    - t
    - inc
requires:
  BerkeleyDB::Manager: '0'
  CHI: '0'
  CHI::Driver: '0'
  Test::More: '0'
version: '0.01'
